-- AlterTable
ALTER TABLE `coveragearea` ADD COLUMN `provinsi` VARCHAR(191) NULL,
    ADD COLUMN `singkatan` VARCHAR(191) NULL,
    MODIFY `status` ENUM('TERSEDIA', 'SEGERA_HADIR', 'TIDAK_TERSEDIA') NOT NULL DEFAULT 'TERSEDIA';
